export const fallbackImage =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="640" height="420" viewBox="0 0 640 420"><rect width="640" height="420" fill="%23F8FAFC"/><rect x="180" y="110" width="280" height="180" rx="18" fill="%23ffffff" stroke="%23E5E7EB" stroke-width="4"/><path d="M224 251l62-65 42 43 31-29 57 51" fill="none" stroke="%23F97316" stroke-width="14" stroke-linecap="round" stroke-linejoin="round"/><circle cx="395" cy="158" r="22" fill="%231E3A8A"/><text x="320" y="334" text-anchor="middle" font-family="Arial, sans-serif" font-size="24" font-weight="700" fill="%230F172A">Image unavailable</text></svg>';

export const products = [
  {
    id: 'acc-cement',
    brand: 'ACC Cement',
    name: 'ACC Suraksha Power Cement',
    category: 'Cement',
    price: 'Rs. 300',
    discountedPrice: 'Rs. 270',
    oldPrice: 'Rs. 300',
    discountPercent: 10,
    unit: 'bag',
    status: 'In Stock',
    rating: 4.0,
    reviews: 12,
    badge: '10% OFF',
    vendor: 'Authorized Distributor',
    shortDescription: 'Durable PPC cement for slabs, masonry, plastering, and everyday site work.',
    description: 'High-performance cement for durable slabs, masonry, and general construction work. Suitable for residential, commercial, and small infrastructure projects.',
    imageUrl: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=800&q=80',
    delivery: 'Delivery in 24-48 hours across major serviceable pin codes.',
    specifications: {
      Brand: 'ACC Cement',
      Category: 'Cement',
      Grade: 'PPC',
      Weight: '50 kg',
      'Material Type': 'Portland Pozzolana Cement',
      Unit: 'Per bag',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'birla-putty',
    brand: 'Birla White',
    name: 'Birla White Wall Putty',
    category: 'Cement',
    price: 'Rs. 920',
    discountedPrice: 'Rs. 840',
    oldPrice: 'Rs. 920',
    discountPercent: 9,
    unit: '40 kg bag',
    status: 'Limited Stock',
    rating: 4.5,
    reviews: 44,
    badge: 'Best Value',
    vendor: 'Birla Partner Store',
    shortDescription: 'Smooth wall putty for refined finishes before paint application.',
    description: 'Premium wall putty for smooth interior and exterior wall finishing before paint. Helps improve paint coverage and wall surface quality.',
    imageUrl: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80',
    delivery: 'Limited stock. Dispatch depends on warehouse availability.',
    specifications: {
      Brand: 'Birla White',
      Category: 'Cement',
      Grade: 'Premium Finish',
      Weight: '40 kg',
      'Material Type': 'White Cement Putty',
      Unit: 'Per 40 kg bag',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'tata-tmt',
    brand: 'Tata Tiscon',
    name: 'Tata Tiscon 550SD TMT Bars',
    category: 'Steel & TMT',
    price: 'Rs. 66,000',
    discountedPrice: 'Rs. 64,500',
    oldPrice: 'Rs. 66,000',
    discountPercent: 2,
    unit: 'MT',
    status: 'In Stock',
    rating: 4.8,
    reviews: 112,
    badge: 'Bulk Deal',
    vendor: 'Tata Steel Limited',
    shortDescription: 'High-strength TMT bars for reinforced concrete and structural projects.',
    description: 'Strong, ductile TMT bars designed for reinforced concrete structures and large projects. Ideal for beams, columns, slabs, and foundation work.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=800&q=80',
    delivery: 'Bulk dispatch by truckload with scheduled site delivery.',
    specifications: {
      Brand: 'Tata Tiscon',
      Category: 'Steel & TMT',
      Grade: '550SD',
      Weight: 'As ordered',
      'Material Type': 'Thermo Mechanically Treated Steel',
      Unit: 'Per MT',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'century-plywood',
    brand: 'Centuryply',
    name: 'Centuryply Sainik 710 Plywood',
    category: 'Plywood',
    price: 'Rs. 385',
    discountedPrice: 'Rs. 350',
    oldPrice: 'Rs. 385',
    discountPercent: 9,
    unit: 'sq.ft',
    status: 'In Stock',
    rating: 4.2,
    reviews: 26,
    vendor: 'Centuryply Direct',
    shortDescription: 'Reliable plywood for furniture, interiors, and commercial fit-outs.',
    description: 'Water-resistant plywood suitable for furniture, partitions, and interior fit-out work. Built for consistent quality across project-scale requirements.',
    imageUrl: 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?auto=format&fit=crop&w=800&q=80',
    delivery: 'Available for warehouse pickup and local delivery.',
    specifications: {
      Brand: 'Centuryply',
      Category: 'Plywood',
      Grade: '710',
      Weight: 'Varies by sheet',
      'Material Type': 'Plywood',
      Unit: 'Per sq.ft',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'kajaria-tiles',
    brand: 'Kajaria',
    name: 'Kajaria Vitrified Floor Tiles',
    category: 'Tiles',
    price: 'Rs. 92',
    discountedPrice: 'Rs. 78',
    oldPrice: 'Rs. 92',
    discountPercent: 15,
    unit: 'sq.ft',
    status: 'In Stock',
    rating: 4.6,
    reviews: 63,
    badge: 'Project Rate',
    vendor: 'Kajaria Channel Partner',
    shortDescription: 'Durable vitrified tiles for commercial and residential flooring.',
    description: 'Low-maintenance vitrified floor tiles with consistent finish, suitable for high-traffic interiors and project use.',
    imageUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80',
    delivery: 'Packed box delivery with breakage-safe handling.',
    specifications: {
      Brand: 'Kajaria',
      Category: 'Tiles',
      Grade: 'Vitrified',
      Weight: 'Box quantity',
      'Material Type': 'Ceramic/Vitrified',
      Unit: 'Per sq.ft',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'asian-paints-emulsion',
    brand: 'Asian Paints',
    name: 'Interior Emulsion Paint 20L',
    category: 'Paints',
    price: 'Rs. 5,200',
    discountedPrice: 'Rs. 4,850',
    oldPrice: 'Rs. 5,200',
    discountPercent: 7,
    unit: 'bucket',
    status: 'Limited Stock',
    rating: 4.6,
    reviews: 35,
    vendor: 'Paints Hub Distributor',
    shortDescription: 'Smooth interior emulsion for long-lasting wall finish.',
    description: 'Premium interior emulsion paint designed for consistent coverage, smooth finish, and reliable project-scale application.',
    imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=800&q=80',
    delivery: 'Same-city delivery available for selected shades.',
    specifications: {
      Brand: 'Asian Paints',
      Category: 'Paints',
      Grade: 'Interior',
      Weight: '20L',
      'Material Type': 'Emulsion Paint',
      Unit: 'Per bucket',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'havells-wire',
    brand: 'Havells',
    name: 'FR PVC Insulated Copper Wire',
    category: 'Electrical',
    price: 'Rs. 3,150',
    discountedPrice: 'Rs. 2,950',
    oldPrice: 'Rs. 3,150',
    discountPercent: 6,
    unit: 'coil',
    status: 'In Stock',
    rating: 4.7,
    reviews: 41,
    vendor: 'Electrical Depot',
    shortDescription: 'Flame-retardant copper wire for safe electrical installations.',
    description: 'FR PVC insulated copper wire suitable for residential and commercial wiring with reliable conductivity and safety standards.',
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    delivery: 'Dispatch within 24 hours for standard coil quantities.',
    specifications: {
      Brand: 'Havells',
      Category: 'Electrical',
      Grade: 'FR PVC',
      Weight: 'Coil',
      'Material Type': 'Copper Wire',
      Unit: 'Per coil',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'astral-cpvc',
    brand: 'Astral Pipes',
    name: 'Astral CPVC Plumbing Pipe',
    category: 'Plumbing',
    price: 'Rs. 520',
    discountedPrice: 'Rs. 450',
    oldPrice: 'Rs. 520',
    discountPercent: 13,
    unit: 'piece',
    status: 'In Stock',
    rating: 4.9,
    reviews: 210,
    badge: 'Contractor Rate',
    vendor: 'Astral Pipes Dealer',
    shortDescription: 'High-pressure CPVC pipe for hot and cold water plumbing.',
    description: 'Reliable CPVC plumbing pipe for domestic and commercial installations, designed for durability and pressure performance.',
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    delivery: 'Available in bundled project quantities.',
    specifications: {
      Brand: 'Astral Pipes',
      Category: 'Plumbing',
      Grade: 'CPVC',
      Weight: 'Standard length',
      'Material Type': 'CPVC',
      Unit: 'Per piece',
      'Country of Origin': 'India',
    },
  },
  {
    id: 'hammer-drill',
    brand: 'Pro-Tools',
    name: 'Industrial Rotary Hammer Drill',
    category: 'Power Tools',
    price: 'Rs. 9,500',
    discountedPrice: 'Rs. 8,900',
    oldPrice: 'Rs. 9,500',
    discountPercent: 6,
    unit: 'unit',
    status: 'Out of Stock',
    rating: 4.9,
    reviews: 18,
    badge: 'New Arrival',
    vendor: 'InfraMart Direct',
    shortDescription: 'Site-ready rotary hammer drill for drilling, chiseling, and fastening.',
    description: 'Heavy-duty rotary hammer drill for site drilling, chiseling, and concrete fastening tasks. Built for rugged daily use on construction sites.',
    imageUrl: null,
    delivery: 'Restock expected soon. Request quote for advance booking.',
    specifications: {
      Brand: 'Pro-Tools',
      Category: 'Power Tools',
      Grade: 'Industrial',
      Weight: '5 kg',
      'Material Type': 'Power Tool',
      Unit: 'Per unit',
      'Country of Origin': 'India',
    },
  },
];

export const getProductById = (id) => products.find((product) => product.id === id);
